trigger:
  paths:
    include:
      - terraform/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python 3.8'
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'v0.12.28'
  displayName: 'Install Terraform'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: 'terraform'
    backendType: 'azurerm'
    backendServiceArm: '...'
    backendAzureRmResourceGroupName: '...'
    backendAzureRmStorageAccountName: '...'
    backendAzureRmContainerName: '...'
    backendAzureRmKey: '...'
  displayName: 'terraform init'
- task: TerraformCLI@0
  inputs:
    command: 'validate'
    provider: 'azurerm'
    workingDirectory: 'terraform'
  displayName: 'terraform validate'
- script: pip install bridgecrew
  displayName: 'Install the Bridgecrew CLI'
- script: bridgecrew -d terraform --bc-api-key abcd1234 --repo-id my_org/my_repo --branch master
  displayName: 'Scan with Bridgecrew'
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: 'terraform'
    environmentServiceName: '...'
  displayName: 'terraform apply'